import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SmoothScrolling from "./components/SmoothScrolling";
import PageTransition from "./components/PageTransition";

const ulmGrotesk = localFont({
  src: [
    {
      path: "../fonts/FontsFreeNetUlmGroteskBold94d4299a1cff25d0157b7ed7aea3accf 1.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/FontsFreeNetUlmGroteskExtrabold0b3118a57784e4d175edb3a9cba99b321.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-ulm-grotesk",
});

const akzidenzGrotesk = localFont({
  src: "../fonts/FontsFreeNetAkzidenzGroteskBlack.ttf",
  variable: "--font-akzidenz-grotesk",
  weight: "900",
});

const coconutMovie = localFont({
  src: "../fonts/FontsFreeNetCoconutMovieDemoRegular.ttf",
  variable: "--font-coconut-movie",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${ulmGrotesk.variable} ${akzidenzGrotesk.variable} ${coconutMovie.variable} antialiased`}
      >
        <SmoothScrolling>
          <PageTransition>
            {children}
          </PageTransition>
        </SmoothScrolling>
      </body>
    </html>
  );
}
