import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SmoothScrolling from "./components/SmoothScrolling";
import PageTransition from "./components/PageTransition";

const layGrotesk = localFont({
  src: [
    {
      path: "../fonts/LayGrotesk-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/LayGrotesk-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-lay-grotesk",
});

const ftSystemMono = localFont({
  src: "../fonts/FTSystemMono-Medium.woff2",
  variable: "--font-ft-system-mono",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${layGrotesk.variable} ${ftSystemMono.variable} antialiased`}
      >
        <SmoothScrolling>
          <PageTransition>{children}</PageTransition>
        </SmoothScrolling>
      </body>
    </html>
  );
}
